# Generated by Django 4.2.2 on 2023-06-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='auto_master_wizard_app.manufacturer')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_model_code', models.CharField(max_length=128, unique=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sub_models', to='auto_master_wizard_app.model')),
            ],
            options={
                'db_table': 'sub_models',
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_code', models.CharField(max_length=128, unique=True)),
                ('sub_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trims', to='auto_master_wizard_app.submodel')),
            ],
            options={
                'db_table': 'trims',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favourites', to='auto_master_wizard_app.profile')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favourites', to='auto_master_wizard_app.trim')),
            ],
            options={
                'db_table': 'favourites',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
                ('url', models.CharField()),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contents', to='auto_master_wizard_app.trim')),
                ('uploading_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contents', to='auto_master_wizard_app.profile')),
            ],
            options={
                'db_table': 'contents',
            },
        ),
    ]
