# Generated by Django 4.2.2 on 2023-06-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_master_wizard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
    ]
