# Generated by Django 4.2.2 on 2023-06-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_master_wizard_app', '0003_profile_trims_trim_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='uploading_profile_id',
            new_name='uploading_profile',
        ),
    ]
