# Generated by Django 4.2.2 on 2023-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_master_wizard_app', '0006_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
