# Generated by Django 4.2.2 on 2023-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_master_wizard_app', '0007_alter_content_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
