# Generated by Django 4.2.2 on 2023-07-23 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_master_wizard_app', '0008_content_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_master_wizard_app.content')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auto_master_wizard_app.project')),
            ],
            options={
                'db_table': 'project_contents',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contents',
            field=models.ManyToManyField(related_name='content_projects', through='auto_master_wizard_app.ProjectContent', to='auto_master_wizard_app.content'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='projects',
            field=models.ManyToManyField(related_name='project_contents', through='auto_master_wizard_app.ProjectContent', to='auto_master_wizard_app.project'),
        ),
    ]
