# Generated by Django 4.2.2 on 2023-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_master_wizard_app', '0009_project_projectcontent_project_contents_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
